### ISSUE TITLE
CompareMultipleSpdxDocs return some false positives in FileFoundLicenses (different instead of equal)

### ISSUE THREAD

**Issue by alpianon** [spdx/tools#267]
I tested the CompareMultipleSpdxDocs function against two spdx files describing `util-linux-2.35.1` and `util-linux-2.36.1` (that I attach here: [util-linux-compare-test.zip](https://github.com/spdx/tools/files/5961685/util-linux-compare-test.zip)) using the following command:

`java -jar ./spdx-tools-2.2.4-jar-with-dependencies.jar CompareMultipleSpdxDocs util-linux-compare.xls util-linux-2.35.1.spdx util-linux-2.36.1.spdx`

In the "File Found Licenses" tab of the output xls file (attached here: [util-linux-compare-xls.zip](https://github.com/spdx/tools/files/5961790/util-linux-compare-xls.zip)), I found the following false positives (files marked as "different" while found licenses are identical)

![screenshot](https://user-images.githubusercontent.com/3025020/107576537-91a91600-6bf1-11eb-8a5e-686213a6879a.png)

The false positives are `./config/ltmain.sh`  `./configure` and  `./m4/libtool.m4`
I checked also in the (attached) spdx files, LicenseInfoInFile data of such files are identical.

eg. the entry for  `./config/ltmain.sh` looks identical in `util-linux-2.35.1.spdx` and in `util-linux-2.36.1.spdx`

```yml
# File

FileName: ./config/ltmain.sh
FileChecksum: SHA1: 031f7e2297cd59a8861bf9854bfadf81dc3d6d8b
LicenseConcluded: NOASSERTION
LicenseInfoInFile: GPL-2.0-or-later
LicenseInfoInFile: GPL-3.0-or-later
LicenseInfoInFile: GPL-3.0-or-later
LicenseInfoInFile: Libtool-exception
LicenseInfoInFile: Libtool-exception
FileCopyrightText: <text>Copyright (c) 1996-2015 Free Software Foundation, Inc.
Copyright (c) 2004-2015 Free Software Foundation, Inc.
Copyright (c) 2010-2015 Free Software Foundation, Inc.
</text>
```

If one wants to process the data stored in the xls file with automated tools in order -- for example -- to weigh the difference between different package versions, false positives do constitute an issue.
